export const COLOR_TEXT_PRIMARY = '#16056B';
export const COLOR_TEXT_SECONDARY = '#6F7FAF';
export const COLOR_BACKGROUND = '#F9F9FF';
export const COLOR_BACKGROUND_BUTTON_PRIMARY = '#16056B';
export const COLOR_PAGINATION_DOT = '#B7D8E7';
export const COLOR_PAGINATION_DOT_ACTIVE = '#6A3BF1';
